### ISSUE TITLE
Dynamically change the kernel startup parameters

### ISSUE THREAD

**Issue by andrus** [dflib/jjava#12]
Maybe there's a more dynamic way to pass the JVM startup arguments to the Java kernel than including them in `kernel.json`. Would be great it those can be set as environment vars, or in some `$HOME/.jupyterc` file, etc. I suppose we'll need a shell script to start java in this case, which will make it OS-dependent (or just use the main JVM to start another JVM?)

**Comment by andrus** [comment]
@m-dzianishchyts , @stariy95 I see there was a PR that went in for this. Let's make sure we mention the new var in README.md docs

**Comment by stariy95** [comment]
@andrus Yep, PR #18 added Python launcher that uses `JJ_JVM_OPTS` to pass additional args to the Java process.
Will add notes to the docs about it.

**Comment by stariy95** [comment]
Close this for now. If we'll need something other than env var to control startup parameters we could open another issue.
