### ISSUE TITLE
Rendering stale var

### ISSUE THREAD

**Issue by andrus** [dflib/jjava#21]
Just noticed this happenning out of the blue (it worked before on the same version of Jupyter and jjava). Consider the following code:

```java
var df1 = Csv.load("../data/games.csv");
df1
```
1. I run the notebook cell in Jupyter once, it prints the contexts of the CSV
2. I change one cell in `games.csv` in a text editor, save
3. Rerun the cell above. It still displays the old data

The few ways to get it unstuck:

* restart the kernel
* make change in a copy of the file with a different name

**Comment by stariy95** [comment]
It was caused by the memory leak fix (#4), different snippets could share the same class and we didn't check for that.
