### ISSUE TITLE
An older jar is used instead of the one indicated in %%loadFromPOM

### ISSUE THREAD

**Issue by r0x07k** [dflib/jjava#31]
While debugging the https://github.com/milvus-io/milvus-sdk-java/issues/1040 issue I found out that JJava is using a random jar version for some reason.

Here is the reproduction:

```
%%loadFromPOM
    <dependency>
        <groupId>com.google.code.gson</groupId>
        <artifactId>gson</artifactId>
        <version>2.10.1</version>
    </dependency>

import com.google.gson.JsonElement;
import com.google.gson.JsonParser;

String jsonString = "{\"name\":\"John\", \"age\":30}";
// This method is available in Gson 2.8.6 and later
JsonElement jsonElement = JsonParser.parseString(jsonString);
System.out.println(jsonElement);
```

The error:
```
|   JsonElement jsonElement = JsonParser.parseString(jsonString);
cannot find symbol
  symbol:   method parseString(java.lang.String)
```

So, the 2.8.5 or older version is used in fact. The same code works fine if run as a normal Java SE application.

**Comment by andrus** [comment]
Hi Pavel, thanks for reporting the issue. Feels like one of the many issues with Ivy (the current dependency management engine we inherited from iJava). I'll try to reproduce and see if there's a a fix. On the longer run we'll switch to Maven for this (see #23). 

FWIW, there's a somewhat heavy-handed way to resolve at least some of the dependency issues: `rm -rf ~/.ivy2/cache/`

**Comment by r0x07k** [comment]
Hi Andrus,

Thank you for letting me know!

**Comment by andrus** [comment]
Ah, everything is simpler than I thought. The base Jupyter kernel that JJava uses has a transitive dependency on `com.google.code.gson:gson:2.8.5`. I opened #33 to port the base kernel code to JJava and update the dependencies.

**Comment by r0x07k** [comment]
That's an interesting root cause :). Thank you for discovering it!

**Comment by stariy95** [comment]
`JJava` now shades `gson` (and other 3rd-party dependencies) so this should be not a problem anymore.
