### ISSUE TITLE
JJ_DISABLE_EXTENSIONS variable

### ISSUE THREAD

**Issue by andrus** [dflib/jjava#38]
There should be a way to start the kernel with no extensions (see #28), and hence, with no implicit imports, and such. Let's introduce a variable that would allow to do that:

```
export JJ_DISABLE_EXTENSIONS=1
```

**Comment by stariy95** [comment]
There's already `JJAVA_LOAD_EXTENSIONS` env var. So `export JJAVA_LOAD_EXTENSIONS=0` would disable extensions.

**Comment by andrus** [comment]
Ah, sorry. You are right. I was looking at the docs last night and it wasn't there.
