### ISSUE TITLE
Hardcoded python location in kernel.json breaks after a homebrew upgrade of Jupyter

### ISSUE THREAD

**Issue by andrus** [dflib/jjava#50]
I had jupyter 4.2.3 installed on MacOS via Homebrew. jjava is installed outside of Jupyter under `~/Library/Jupyter/kernels/java`. 

Recently upgraded Jupyter to 4.2.5 via brew. Now the kernel fails to start (see the attached screenshot) , because `kernel.json` has version-specific Python location of `"/opt/homebrew/Cellar/jupyterlab/4.2.3/libexec/bin/python"`. Fixing it required kernel reinstall.

<img width="833" alt="Untitled" src="https://github.com/user-attachments/assets/60ed3f5e-8ce2-4f42-9df8-8cba0f92e448">

Hopefully this issue will go away on its own after #35 is released in M4, that feature a pure Java, Python-free kernel startup script

**Comment by stariy95** [comment]
`1.0-a4` release is out, so no more `install.py` or any other dependency on a Python
