### ISSUE TITLE
Update JJava configuration documentation 

### ISSUE THREAD

**Issue by stariy95** [dflib/jjava#51]
See discussion here: https://github.com/dflib/jjava/issues/44#issuecomment-2417532573

In short: after #35 is done, we need to review configuration documentation. Also it may worth mentioning the possibility (and limitations) of manual editing the `kernel.json` file.

**Comment by stariy95** [comment]
As a note, here's an official docs about `kernel.json` format: https://jupyter-client.readthedocs.io/en/stable/kernels.html#kernel-specs

**Comment by andrus** [comment]
done, the new docs are published - https://dflib.org/jjava/docs/1.x/#_configuring
