### ISSUE TITLE
Black error message in dark mode (e.g. VSCode) not easily readable

### ISSUE THREAD

**Issue by emcastro** [dflib/jjava#57]
Use of ANSI control characters is annoying when using VSCode Jupyter in standard dark mode. Some error messages are written black on dark gray.
![image](https://github.com/user-attachments/assets/bebfe1c1-b8e6-4b6e-af53-9901e0443152)
Try to read the message `|     null.toString()`!

**Comment by andrus** [comment]
We'll track it under #24

**Comment by emcastro** [comment]
> We'll track it under #24

They are different problems. The issue with VSCode is just inadequate use of BOLD_BLACK_FG color, which is black regardless of the theme of the terminal, instead of BOLD_REST_FG which is black in Jupyter Lab and white in dark TTY (including VSCode).

The solution was easy (cf. merge request #58). I use it at home. it works well with VSCode and Jupyter Lab.

For #24, the problem is to determine the standard way to detect that ANSI colors should not be used.

**Comment by andrus** [comment]
Ok, looks I was a bit too rush to combine the two issues. Reopening.

**Comment by andrus** [comment]
Merged #58. Thanks!
