### ISSUE TITLE
Project renaming

### ISSUE THREAD

**Issue by stariy95** [dflib/jjava#7]
Name of choice for this project is `JJava`, need to review and change it where needed.
Also we need to keep in mind compatibility at the Jupyter level, so it won't require to change existing code.

**Comment by andrus** [comment]
Hey guys, @stariy95 @m-dzianishchyts , we just renamed all the env vars from `IJAVA_` to `JJAVA_`, which is fine, but I suggest that we support the old vars as well for some time as deprecated. I would like JJava to stay compatible with iJava for some time.
